export const zones = [
  {
    id: 1,
    name: 'dolnośląskie',
    unique_name: 'dolnoslaskie',
    name_locative: 'dolnośląskim',
  },
  {
    id: 2,
    name: 'kujawsko-pomorskie',
    unique_name: 'kujawsko-pomorskie',
    name_locative: 'kujawsko-pomorskim',
  },
  {
    id: 3,
    name: 'lubelskie',
    unique_name: 'lubelskie',
    name_locative: 'lubelskim',
  },
  {
    id: 4,
    name: 'lubuskie',
    unique_name: 'lubuskie',
    name_locative: 'lubuskim',
  },
  {
    id: 5,
    name: 'łódzkie',
    unique_name: 'lodzkie',
    name_locative: 'łódzkim',
  },
  {
    id: 6,
    name: 'małopolskie',
    unique_name: 'malopolskie',
    name_locative: 'małopolskim',
  },
  {
    id: 7,
    name: 'mazowieckie',
    unique_name: 'mazowieckie',
    name_locative: 'mazowieckim',
  },
  {
    id: 8,
    name: 'opolskie',
    unique_name: 'opolskie',
    name_locative: 'opolskim',
  },
  {
    id: 9,
    name: 'podkarpackie',
    unique_name: 'podkarpackie',
    name_locative: 'podkarpackim',
  },
  {
    id: 10,
    name: 'podlaskie',
    unique_name: 'podlaskie',
    name_locative: 'podlaskim',
  },
  {
    id: 11,
    name: 'pomorskie',
    unique_name: 'pomorskie',
    name_locative: 'pomorskim',
  },
  {
    id: 12,
    name: 'śląskie',
    unique_name: 'slaskie',
    name_locative: 'śląskim',
  },
  {
    id: 13,
    name: 'świętokrzyskie',
    unique_name: 'swietokrzyskie',
    name_locative: 'świętokrzyskim',
  },
  {
    id: 14,
    name: 'warmińsko-mazurskie',
    unique_name: 'warminsko-mazurskie',
    name_locative: 'warmińsko-mazurskim',
  },
  {
    id: 15,
    name: 'wielkopolskie',
    unique_name: 'wielkopolskie',
    name_locative: 'wielkopolskim',
  },
  {
    id: 16,
    name: 'zachodniopomorskie',
    unique_name: 'zachodniopomorskie',
    name_locative: 'zachodniopomorskim',
  },
];

export const companyZones = [
  { viewValue: 'Dolnośląskie', value: 'DS' },
  { viewValue: 'Kujawsko', value: 'KP' },
  { viewValue: 'Lubelskie', value: 'LU' },
  { viewValue: 'Lubuskie', value: 'LB' },
  { viewValue: 'Łódzkie', value: 'LD' },
  { viewValue: 'Małopolskie', value: 'MP' },
  { viewValue: 'Mazowieckie', value: 'MA' },
  { viewValue: 'Opolskie', value: 'OP' },
  { viewValue: 'Podkarpackie', value: 'PK' },
  { viewValue: 'Podlaskie', value: 'PD' },
  { viewValue: 'Pomorskie', value: 'PM' },
  { viewValue: 'Śląskie', value: 'SL' },
  { viewValue: 'Świętokrzyskie', value: 'SW' },
  { viewValue: 'Warmińsko', value: 'WM' },
  { viewValue: 'Wielkopolskie', value: 'WP' },
  { viewValue: 'Zachodniopomorskie', value: 'ZP' },
];
